# Auto-generated by tools/deploy.py from config.py + .env — do not commit.
WIFI_SSID          = ''
WIFI_PASSWORD      = ''
WIFI_NETWORKS      = []
WIFI_AUTO_CONNECT  = True
BT_AUTO_ENABLE     = False
GITHUB_USER        = 'Circuit-Overtime'
DISPLAY_NAME       = 'Ayushman Bhattacharya'
DESIGNATION        = 'Developer @Myceli.ai'
OWM_API_KEY        = ''
WEATHER_LAT        = 22.57
WEATHER_LON        = 88.36
WEATHER_NAME       = ''
TIMEZONE_OFFSET    = 5.5
WIFI_TX_DBM        = 11
WIFI_POWERSAVE     = True
BT_ADV_INTERVAL_MS = 500
