"""Static web templates and HTML pages served by oreoOS.http_server."""

_UPLOAD_FORM = (
    b"<!doctype html><html lang='en'><head>"
    b"<meta name='viewport' content='width=device-width,initial-scale=1'>"
    b"<meta name='theme-color' content='#0F0C1C'>"
    b"<title>Send to Oreo</title>"
    b"<style>"
    b":root{--bg:#0F0C1C;--card:#1C1A2E;--cardb:#26213E;--bord:#2A2640;"
    b"--ink:#F5E6DC;--dim:#C8B8B0;--mute:#8A8294;--pri:#FF5D68;"
    b"--gold:#FFD166;--teal:#3DDC97;--lilac:#A29BFE}"
    b"*{box-sizing:border-box}"
    b"html,body{margin:0;padding:0;background:var(--bg);color:var(--ink);"
    b"font-family:-apple-system,system-ui,Segoe UI,Roboto,sans-serif;"
    b"-webkit-font-smoothing:antialiased;min-height:100vh}"
    b"body{display:flex;flex-direction:column;align-items:center;"
    b"justify-content:center;padding:32px 16px;"
    b"background-image:radial-gradient(60% 50% at 20% 0%,rgba(255,93,104,.12),transparent 60%),"
    b"radial-gradient(50% 45% at 85% 100%,rgba(162,155,254,.08),transparent 60%)}"
    b".brand{display:flex;flex-direction:column;align-items:center;gap:10px;margin-bottom:18px}"
    b".brand .mascot{width:84px;height:84px;border-radius:18px;"
    b"background:var(--card);border:1px solid rgba(255,93,104,.4);"
    b"padding:6px;box-shadow:0 0 30px rgba(255,93,104,.25);object-fit:contain}"
    b".brand h1{margin:0;font-size:22px;font-weight:600;letter-spacing:-.01em}"
    b".panel{width:100%;max-width:440px;background:var(--card);border:1px solid var(--bord);"
    b"border-radius:14px;overflow:hidden}"
    b".pad{padding:24px}"
    b"h2{margin:0 0 6px;font-size:18px;font-weight:600}"
    b".sub{margin:0;color:var(--dim);font-size:13px;line-height:1.55}"
    b".chip{display:inline-flex;align-items:center;gap:6px;padding:4px 10px;border-radius:999px;"
    b"font-size:11px;text-transform:uppercase;letter-spacing:.12em;background:var(--cardb);color:var(--dim)}"
    b".pulse{display:inline-block;width:8px;height:8px;border-radius:5px;background:var(--gold);"
    b"margin-right:8px;vertical-align:middle;animation:p 1.4s ease-in-out infinite}"
    b"@keyframes p{0%,100%{opacity:.25;transform:scale(.85)}50%{opacity:1;transform:scale(1)}}"
    b".code-row{display:flex;gap:8px;justify-content:center;margin:14px 0 4px}"
    b".code-row input{width:46px;height:58px;border-radius:8px;border:1px solid var(--bord);"
    b"background:var(--bg);color:var(--pri);text-align:center;font-size:30px;font-weight:600;"
    b"font-family:ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;outline:none}"
    b".code-row input:focus{border-color:var(--pri);box-shadow:0 0 0 3px rgba(255,93,104,.22)}"
    b".did{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:30px;"
    b"letter-spacing:.32em;color:var(--teal);margin:14px 0 4px;text-align:center;"
    b"text-shadow:0 0 30px rgba(61,220,151,.35)}"
    b".drop{display:block;width:100%;border:2px dashed var(--bord);border-radius:10px;"
    b"padding:22px 18px;text-align:center;box-sizing:border-box;"
    b"cursor:pointer;transition:.2s border-color,.2s background;background:rgba(38,33,62,.4)}"
    b".drop:hover,.drop.over{border-color:var(--pri);background:rgba(255,93,104,.06)}"
    b".drop input{display:none}"
    b".drop .icon{font-size:30px;color:var(--pri);margin-bottom:4px;line-height:1}"
    b".drop .l1{font-weight:600;margin:6px 0 2px;font-size:14px}"
    b".drop .l2{margin:0;color:var(--mute);font-size:12px}"
    b".preview{display:none;align-items:center;gap:12px;background:var(--cardb);"
    b"border:1px solid var(--bord);border-radius:10px;padding:12px 14px}"
    b".thumb{width:60px;height:60px;border-radius:6px;background:var(--bg);flex-shrink:0;"
    b"display:grid;place-items:center;font-size:20px;color:var(--mute);overflow:hidden}"
    b".thumb img,.thumb video{width:100%;height:100%;object-fit:cover}"
    b".pmeta{flex:1;min-width:0}"
    b".pmeta .n{font-weight:600;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}"
    b".pmeta .s{font-size:12px;color:var(--mute);margin-top:2px}"
    b".btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;"
    b"background:var(--pri);color:var(--bg);border:0;border-radius:8px;padding:13px 18px;"
    b"font-size:15px;font-weight:600;width:100%;cursor:pointer;transition:.15s background}"
    b".btn:hover{background:#C8434C}"
    b".btn:disabled{background:#4A4458;color:var(--mute);cursor:not-allowed}"
    b".btn.ghost{background:transparent;color:var(--ink);border:1px solid var(--bord)}"
    b".btn.ghost:hover{background:var(--cardb)}"
    b".status{display:flex;align-items:center;gap:10px;padding:11px 13px;border-radius:8px;"
    b"background:var(--cardb);font-size:13px;color:var(--dim)}"
    b".status .dot{width:8px;height:8px;border-radius:5px;background:var(--mute)}"
    b".status.live .dot{background:var(--gold);animation:p 1.4s ease-in-out infinite}"
    b".status.ok .dot{background:var(--teal)}"
    b".status.err .dot{background:var(--pri)}"
    b".err-msg{color:var(--pri);font-size:13px;text-align:center;margin:6px 0 0;min-height:18px}"
    b".progress{height:6px;background:var(--bord);border-radius:4px;overflow:hidden;margin-top:14px}"
    b".bar{height:100%;background:linear-gradient(90deg,var(--pri),var(--lilac));"
    b"width:0;transition:width .15s ease-out}"
    b".pct{margin-top:8px;font-size:12px;color:var(--mute);display:flex;justify-content:space-between}"
    b".stack>*+*{margin-top:14px}"
    b".hide{display:none!important}"
    b".foot{margin-top:18px;font-size:11px;color:var(--mute);text-align:center;max-width:440px}"
    b".foot a{color:var(--dim);text-decoration:none;border-bottom:1px dashed var(--bord)}"
    b".mdl{position:fixed;inset:0;background:rgba(15,12,28,.78);"
    b"backdrop-filter:blur(6px);display:none;align-items:center;"
    b"justify-content:center;padding:24px;z-index:50}"
    b".mdl.open{display:flex}"
    b".mdl .box{background:var(--card);border:1px solid var(--bord);"
    b"border-radius:14px;max-width:380px;width:100%;padding:22px;"
    b"box-shadow:0 30px 60px rgba(0,0,0,.5)}"
    b".mdl .ic{width:42px;height:42px;border-radius:10px;"
    b"display:grid;place-items:center;font-size:22px;margin-bottom:12px;"
    b"background:rgba(255,93,104,.15);color:var(--pri)}"
    b".mdl.ok .ic{background:rgba(61,220,151,.15);color:var(--teal)}"
    b".mdl h3{margin:0 0 6px;font-size:17px;font-weight:600}"
    b".mdl p{margin:0 0 16px;color:var(--dim);font-size:13px;line-height:1.55}"
    b".mdl .acts{display:flex;gap:8px}"
    b".mdl .acts .btn{flex:1;padding:11px 14px;font-size:14px}"
    b".reset{margin-top:14px;text-align:center}"
    b".reset button{background:transparent;border:0;color:var(--mute);"
    b"font-size:12px;cursor:pointer;text-decoration:underline;"
    b"text-decoration-color:var(--bord);text-underline-offset:3px}"
    b".reset button:hover{color:var(--ink)}"
    b"</style></head><body>"
    b"<div class='brand'>"
    b"<img class='mascot' src='/mascot.png' alt='Oreo'>"
    b"<h1>Send to Oreo</h1></div>"
    b"<div class='panel'>"
    b"<div id='wait' class='pad stack'>"
    b"<span class='chip'>step 1 of 2</span>"
    b"<h2>Waiting for badge owner</h2>"
    b"<p class='sub'>Your device ID is shown below &mdash; "
    b"it appears on the badge owner's screen too. "
    b"They have to tap <b>A</b> on the matching row to let you send a file.</p>"
    b"<div class='did' id='did'>__DEVICE_ID__</div>"
    b"<div class='status live' id='wstat'><span class='dot'></span>"
    b"<span id='wmsg'>waiting for approval&hellip;</span></div>"
    b"<div class='reset'><button type='button' onclick='resetAll()'>"
    b"Reset transaction</button></div>"
    b"</div>"
    b"<div id='form' class='pad stack hide'>"
    b"<span class='chip' style='background:rgba(61,220,151,.15);color:var(--teal)'>"
    b"approved &middot; <span id='okid' style='font-family:ui-monospace,monospace'>__DEVICE_ID__</span></span>"
    b"<h2>Pick a file to send</h2>"
    b"<p class='sub'>Images and videos are optimised in your browser before upload. "
    b"Video is capped at 10 seconds for smooth fullscreen playback.</p>"
    b"<label class='drop' id='drop'>"
    b"<input id='file' type='file' accept='image/*,video/*,.txt,.md'>"
    b"<div class='icon'>&uarr;</div>"
    b"<p class='l1'>Tap to choose or drop here</p>"
    b"<p class='l2'>PNG &middot; JPG &middot; GIF &middot; MP4 &middot; MOV &middot; WEBM &middot; TXT &middot; MD</p></label>"
    b"<div class='preview' id='preview'>"
    b"<div class='thumb' id='thumb'>?</div>"
    b"<div class='pmeta'><div class='n' id='pname'>&mdash;</div>"
    b"<div class='s' id='psize'>&mdash;</div></div></div>"
    b"<button id='go' class='btn' disabled>Send to badge</button>"
    b"<div class='progress'><div class='bar' id='bar'></div></div>"
    b"<div class='pct hide' id='pct'><span id='pctn'>0%</span>"
    b"<span id='pctb'>0 / 0 KB</span></div>"
    b"<div class='reset'><button type='button' onclick='resetAll()'>"
    b"Reset transaction</button></div></div>"
    b"<div id='done' class='pad stack hide' style='text-align:center'>"
    b"<div style='font-size:42px;color:var(--teal);line-height:1'>&#10003;</div>"
    b"<h2>Sent!</h2><p class='sub'>Open the matching app on your badge to view it.</p>"
    b"<button class='btn' onclick='location.reload()'>Send another</button></div>"
    b"</div>"
    b"<div class='mdl' id='mdl'><div class='box'>"
    b"<div class='ic' id='mdlIc'>!</div>"
    b"<h3 id='mdlT'>Something went wrong</h3>"
    b"<p id='mdlM'>&mdash;</p>"
    b"<div class='acts'>"
    b"<button class='btn ghost' id='mdlNo' onclick='closeModal()'>Dismiss</button>"
    b"<button class='btn' id='mdlYes' onclick='resetAll()'>Reset</button>"
    b"</div></div></div>"
    b"<div class='foot'>Peer-to-peer on your local network &middot; "
    b"Powered by <a href='https://oreo.elixpo.com' target='_blank'>oreo.elixpo.com</a></div>"
    b"<script>"
    b"const $=id=>document.getElementById(id);"
    b"const MAX_DIM=240,VIDEO_W=320,VIDEO_H=240,VIDEO_FPS=20,VIDEO_SECONDS=10,MAX_UPLOAD=8*1024*1024;"
    b"const did=$('did').textContent.trim();"
    b"let approved=false,beaconBusy=false,beaconTimer=null,picked=null,activeXhr=null;"
    b"let freeBytes=0;"
    b"const FREE_HEADROOM=64*1024;"
    b"function fmtKB(n){return (n/1024)<1024?(Math.round(n/1024)+' KB'):"
    b"((n/1024/1024).toFixed(2)+' MB');}"
    b"function setWaitStatus(cls,msg){const s=$('wstat');s.className='status '+cls;$('wmsg').textContent=msg;}"
    b"function showModal(title,msg,kind,resetable){"
    b"  const m=$('mdl');m.className='mdl open'+(kind==='ok'?' ok':'');"
    b"  $('mdlIc').textContent=(kind==='ok'?'\\u2713':'!');"
    b"  $('mdlT').textContent=title;$('mdlM').textContent=msg;"
    b"  $('mdlYes').style.display=resetable===false?'none':'';"
    b"  $('mdlNo').textContent=resetable===false?'OK':'Dismiss';}"
    b"function closeModal(){$('mdl').classList.remove('open');}"
    b"function resetAll(){"
    b"  closeModal();"
    b"  try{if(activeXhr){activeXhr.abort();activeXhr=null;}}catch(e){}"
    b"  if(beaconTimer){clearInterval(beaconTimer);beaconTimer=null;}"
    b"  location.reload();}"
    b"async function beacon(){"
    b"  if(!did||approved||beaconBusy)return;beaconBusy=true;"
    b"  try{const r=await fetch('/beacon?id='+did);"
    b"      if(r.status===410){"
    b"        clearInterval(beaconTimer);"
    b"        $('wait').innerHTML=\"<h2>Session expired</h2><p class='sub'>The "
    b"code rotated or the badge owner closed transfer. "
    b"<button class='btn ghost' onclick='location.reload()'>Try again</button>\";"
    b"        return;}"
    b"      const j=await r.json();"
    b"      if(typeof j.free==='number')freeBytes=j.free;"
    b"      if(j.state==='approved'){approved=true;clearInterval(beaconTimer);"
    b"        $('wait').classList.add('hide');$('form').classList.remove('hide');}"
    b"      else if(j.state==='denied'){clearInterval(beaconTimer);"
    b"        $('wait').innerHTML=\"<h2>Denied</h2><p class='sub'>The badge "
    b"owner rejected this device.</p>"
    b"<button class='btn ghost' onclick='location.reload()'>Try again</button>\";}"
    b"      else{setWaitStatus('live',j.state==='approving'?'approval received\\u2026':'waiting for approval on badge\\u2026');}}"
    b"  catch(e){setWaitStatus('err','badge unreachable - check WiFi');}"
    b"  finally{beaconBusy=false;}}"
    b"function mediaKind(file){"
    b"  const n=file.name.toLowerCase();"
    b"  if(file.type.startsWith('image/')||/\\.(png|jpe?g|gif|webp)$/.test(n))return'image';"
    b"  if(file.type.startsWith('video/')||/\\.(mp4|mov|m4v|webm|avi)$/.test(n))return'video';"
    b"  return'document';}"
    b"function onFile(file){"
    b"  if(!file)return;"
    b"  const kind=mediaKind(file),isImg=kind==='image',isVid=kind==='video';"
    b"  const estDiskBytes=isImg?(240*240*2+6):(isVid?0:file.size);"
    b"  if(freeBytes>0&&estDiskBytes+FREE_HEADROOM>freeBytes){"
    b"    showModal('Not enough space',"
    b"      'This badge only has '+fmtKB(freeBytes)+' free, which is not enough for a '+"
    b"      fmtKB(estDiskBytes)+' file. Delete a photo or document on the badge first.',"
    b"      'err',false);"
    b"    return;}"
    b"  picked=file;"
    b"  $('preview').style.display='flex';$('drop').style.display='none';"
    b"  $('pname').textContent=file.name;$('psize').textContent=fmtKB(file.size);"
    b"  const th=$('thumb');th.innerHTML='';"
    b"  if(isImg){"
    b"    const im=document.createElement('img');im.src=URL.createObjectURL(file);th.appendChild(im);}"
    b"  else if(isVid){"
    b"    const v=document.createElement('video');v.src=URL.createObjectURL(file);"
    b"    v.muted=true;v.playsInline=true;th.appendChild(v);}"
    b"  else{th.textContent=file.name.split('.').pop().toUpperCase();}"
    b"  $('go').disabled=false;}"
    b"async function imgToR565(file){"
    b"  const img=new Image();img.src=URL.createObjectURL(file);"
    b"  await new Promise((r,j)=>{img.onload=r;img.onerror=j;});"
    b"  const sc=Math.min(1,MAX_DIM/Math.max(img.width,img.height));"
    b"  const w=Math.max(1,Math.round(img.width*sc)),h=Math.max(1,Math.round(img.height*sc));"
    b"  const c=document.createElement('canvas');c.width=w;c.height=h;"
    b"  const ctx=c.getContext('2d');"
    b"  ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);"
    b"  const px=ctx.getImageData(0,0,w,h).data;"
    b"  const out=new Uint8Array(6+w*h*2);"
    b"  out[0]=0x52;out[1]=0x35;"
    b"  out[2]=w&0xff;out[3]=(w>>8)&0xff;"
    b"  out[4]=h&0xff;out[5]=(h>>8)&0xff;"
    b"  let o=6;"
    b"  for(let i=0;i<px.length;i+=4){"
    b"    const r=px[i]>>3,g=px[i+1]>>2,b=px[i+2]>>3;"
    b"    const v=(r<<11)|(g<<5)|b;out[o++]=(v>>8)&0xff;out[o++]=v&0xff;}"
    b"  return new Blob([out],{type:'application/octet-stream'});}"
    b"function encodeDelta(cur,prev){"
    b"  const out=[];let p=0,n=cur.length;"
    b"  while(p<n){"
    b"    if(cur[p]===prev[p]){let k=1;while(k<64&&p+k<n&&cur[p+k]===prev[p+k])k++;"
    b"      out.push(k-1);p+=k;continue;}"
    b"    let run=1;while(run<64&&p+run<n&&cur[p+run]===cur[p]&&cur[p+run]!==prev[p+run])run++;"
    b"    if(run>=3){const v=cur[p];out.push(0x80|(run-1),v>>8,v&255);p+=run;continue;}"
    b"    const start=p;p++;"
    b"    while(p<n&&p-start<64&&cur[p]!==prev[p]){"
    b"      let r=1;while(r<3&&p+r<n&&cur[p+r]===cur[p]&&cur[p+r]!==prev[p+r])r++;"
    b"      if(r>=3)break;p++;}"
    b"    out.push(0x40|(p-start-1));"
    b"    for(let i=start;i<p;i++){out.push(cur[i]>>8,cur[i]&255);}"
    b"  }return new Uint8Array(out);}"
    b"async function compressFrame(raw){"
    b"  if(typeof CompressionStream==='undefined')throw new Error('this browser cannot compress video frames');"
    b"  const stream=new Blob([raw]).stream().pipeThrough(new CompressionStream('deflate'));"
    b"  return new Uint8Array(await new Response(stream).arrayBuffer());}"
    b"async function videoToRV565(file){"
    b"  const url=URL.createObjectURL(file),v=document.createElement('video');"
    b"  v.muted=true;v.playsInline=true;v.preload='auto';v.src=url;"
    b"  try{await new Promise((r,j)=>{v.onloadeddata=r;v.onerror=()=>j(new Error('unsupported video'));});"
    b"    const dur=Math.min(v.duration,VIDEO_SECONDS);"
    b"    if(!isFinite(dur)||dur<=0)throw new Error('video has no readable duration');"
    b"    const w=VIDEO_W,h=VIDEO_H;"
    b"    const count=Math.max(1,Math.floor(dur*VIDEO_FPS));"
    b"    const head=new Uint8Array(12);head.set([82,86,53,2]);"
    b"    head[4]=w&255;head[5]=w>>8;head[6]=h&255;head[7]=h>>8;"
    b"    head[8]=VIDEO_FPS;head[10]=count&255;head[11]=count>>8;"
    b"    const chunks=[head];"
    b"    const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');"
    b"    for(let f=0;f<count;f++){"
    b"      const t=Math.min(f/VIDEO_FPS,Math.max(0,dur-.001));"
    b"      if(Math.abs(v.currentTime-t)>.001){await new Promise((r,j)=>{v.onseeked=r;v.onerror=j;v.currentTime=t;});}"
    b"      const sc=Math.max(w/v.videoWidth,h/v.videoHeight);"
    b"      const dw=v.videoWidth*sc,dh=v.videoHeight*sc;"
    b"      ctx.drawImage(v,(w-dw)/2,(h-dh)/2,dw,dh);"
    b"      const rgba=ctx.getImageData(0,0,w,h).data;"
    b"      const raw=new Uint8Array(w*h*2);"
    b"      for(let i=0,o=0;i<rgba.length;i+=4,o++){let px=((rgba[i]>>3)<<11)|((rgba[i+1]>>2)<<5)|(rgba[i+2]>>3);px&=0xF79E;raw[o*2]=px>>8;raw[o*2+1]=px&255;}"
    b"      const enc=await compressFrame(raw),sz=new Uint8Array(4),n=enc.length;"
    b"      sz[0]=n&255;sz[1]=(n>>8)&255;sz[2]=(n>>16)&255;sz[3]=(n>>24)&255;"
    b"      chunks.push(sz,enc);"
    b"      $('pctn').textContent='Optimising '+Math.round((f+1)*100/count)+'%';"
    b"      if((f&3)===3)await new Promise(r=>setTimeout(r,0));}"
    b"    return new Blob(chunks,{type:'application/octet-stream'});"
    b"  }finally{URL.revokeObjectURL(url);}}"
    b"async function send(){"
    b"  if(!picked||!did)return;$('go').disabled=true;$('pct').classList.remove('hide');"
    b"  let payload=picked,name=picked.name;"
    b"  const kind=mediaKind(picked);"
    b"  if(kind==='image'){"
    b"    try{payload=await imgToR565(picked);name=name.replace(/\\.[^.]+$/,'')+'.r565';}"
    b"    catch(err){"
    b"      showModal('Image decode failed',String(err),'err',true);"
    b"      $('go').disabled=false;return;}}"
    b"  else if(kind==='video'){"
    b"    try{payload=await videoToRV565(picked);name=name.replace(/\\.[^.]+$/,'')+'.rv565';"
    b"      if(payload.size>MAX_UPLOAD||freeBytes>0&&payload.size+FREE_HEADROOM>freeBytes)"
    b"        throw new Error('optimised video needs '+fmtKB(payload.size)+', but the badge does not have enough space');}"
    b"    catch(err){showModal('Video conversion failed',String(err),'err',true);"
    b"      $('go').disabled=false;return;}}"
    b"  const fd=new FormData();fd.append('f',payload,name);"
    b"  const xhr=new XMLHttpRequest();activeXhr=xhr;"
    b"  xhr.upload.addEventListener('progress',(ev)=>{"
    b"    if(ev.lengthComputable){const p=ev.loaded/ev.total;"
    b"      $('bar').style.width=(p*100)+'%';"
    b"      $('pctn').textContent=Math.round(p*100)+'%';"
    b"      $('pctb').textContent=fmtKB(ev.loaded)+' / '+fmtKB(ev.total);}});"
    b"  xhr.onload=()=>{activeXhr=null;if(xhr.status===200||xhr.status===0){"
    b"    $('form').classList.add('hide');$('done').classList.remove('hide');}"
    b"    else if(xhr.status===403){"
    b"      showModal('Device no longer approved',"
    b"        'The badge owner revoked this session. Reset to start a new one.',"
    b"        'err',true);$('go').disabled=false;}"
    b"    else{showModal('Upload failed','Server returned status '+xhr.status+'.',"
    b"        'err',true);$('go').disabled=false;}};"
    b"  xhr.onerror=()=>{activeXhr=null;"
    b"    const w=parseInt($('bar').style.width)||0;"
    b"    if(w>=99){$('form').classList.add('hide');$('done').classList.remove('hide');return;}"
    b"    showModal('Network error',"
    b"      'Lost connection to the badge. Check that both devices are on the same WiFi, then reset.',"
    b"      'err',true);$('go').disabled=false;};"
    b"  xhr.open('POST','/upload?token='+did);xhr.send(fd);}"
    b"document.addEventListener('DOMContentLoaded',()=>{"
    b"  beaconTimer=setInterval(beacon,500);beacon();"
    b"  $('file').addEventListener('change',e=>onFile(e.target.files[0]));"
    b"  const dz=$('drop');"
    b"  ['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('over');}));"
    b"  ['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('over');}));"
    b"  dz.addEventListener('drop',e=>{if(e.dataTransfer.files[0])onFile(e.dataTransfer.files[0]);});"
    b"  $('go').addEventListener('click',send);});"
    b"</script></body></html>"
)

_DISABLED_PAGE = (
    b"<!doctype html><html><head>"
    b"<meta name='viewport' content='width=device-width,initial-scale=1'>"
    b"<meta name='theme-color' content='#0F0C1C'>"
    b"<title>Transfer disabled</title>"
    b"<style>body{margin:0;padding:48px 24px;background:#0F0C1C;color:#F5E6DC;"
    b"font-family:-apple-system,system-ui,sans-serif;text-align:center}"
    b"h1{color:#FF5D68;font-size:24px;margin:0 0 12px}"
    b"p{color:#C8B8B0;font-size:14px;line-height:1.6;max-width:380px;margin:0 auto}"
    b".mark{display:inline-block;width:38px;height:38px;border-radius:8px;"
    b"border:1px solid rgba(255,93,104,.4);color:#FF5D68;font-weight:700;"
    b"display:grid;place-items:center;margin:0 auto 18px;font-size:20px}"
    b"</style></head><body>"
    b"<div class='mark'>o</div>"
    b"<h1>Transfer is disabled</h1>"
    b"<p>The badge owner has closed file transfer for safety. "
    b"Ask them to re-enable it from the badge's "
    b"<b>Settings &rsaquo; WiFi &rsaquo; Send Files</b> page.</p>"
    b"</body></html>"
)

_NOT_FOUND_PAGE = (
    b"<!doctype html><html lang='en'><head>"
    b"<meta name='viewport' content='width=device-width,initial-scale=1'>"
    b"<meta name='theme-color' content='#0F0C1C'>"
    b"<title>Bad code &middot; Oreo</title>"
    b"<style>"
    b":root{--bg:#0F0C1C;--card:#1C1A2E;--bord:#2A2640;"
    b"--ink:#F5E6DC;--dim:#C8B8B0;--mute:#8A8294;--pri:#FF5D68}"
    b"*{box-sizing:border-box}"
    b"html,body{margin:0;padding:0;background:var(--bg);color:var(--ink);"
    b"font-family:-apple-system,system-ui,sans-serif;min-height:100vh}"
    b"body{display:flex;flex-direction:column;align-items:center;"
    b"justify-content:center;padding:24px;text-align:center;"
    b"background-image:radial-gradient(60% 50% at 20% 0%,rgba(255,93,104,.12),transparent 60%),"
    b"radial-gradient(50% 45% at 85% 100%,rgba(162,155,254,.08),transparent 60%)}"
    b".mark{width:48px;height:48px;border-radius:10px;border:1px solid rgba(255,93,104,.4);"
    b"background:var(--card);display:grid;place-items:center;font-weight:700;"
    b"color:var(--pri);font-size:22px;margin-bottom:18px;"
    b"box-shadow:0 0 30px rgba(255,93,104,.25)}"
    b".code{font-size:60px;font-weight:700;color:var(--pri);margin:0 0 6px;"
    b"line-height:1;letter-spacing:-.02em}"
    b"h1{font-size:22px;margin:8px 0 8px;font-weight:600}"
    b"p{color:var(--dim);font-size:14px;line-height:1.55;max-width:380px;margin:0 0 18px}"
    b".btn{display:inline-flex;align-items:center;gap:8px;background:var(--pri);"
    b"color:var(--bg);border:0;border-radius:8px;padding:12px 20px;"
    b"font-size:14px;font-weight:600;text-decoration:none}"
    b"</style></head><body>"
    b"<div class='mark'>o</div>"
    b"<p class='code'>404</p>"
    b"<h1>Bad or expired code</h1>"
    b"<p>This page only opens when launched from "
    b"<b>oreo.elixpo.com/upload</b> with the current 6-character "
    b"code shown on the badge. The code rotates every 5 minutes "
    b"&mdash; head back and grab a fresh one.</p>"
    b"<a class='btn' href='https://oreo.elixpo.com/upload'>Open oreo.elixpo.com/upload</a>"
    b"</body></html>"
)
